# vantablack theme
window_padding_width 10

# Special
foreground #ffffff
background #000000

# Black
color0  #404040
color8  #5c5c5c

# Red
color1  #a4a4a4
color9  #a4a4a4

# Green
color2  #b6b6b6
color10 #b6b6b6

# Yellow
color3  #cecece
color11 #cecece

# Blue
color4  #8d8d8d
color12 #8d8d8d

# Magenta
color5  #9b9b9b
color13 #9b9b9b

# Cyan
color6  #b0b0b0
color14 #b0b0b0

# White
color7  #ececec
color15 #ffffff

# Cursor
cursor              #ffffff
cursor_text_color   #000000

# Selection
selection_foreground #ffffff
selection_background #0f0f0f

# Tab bar
active_tab_foreground   #000000
active_tab_background   #9b9b9b
active_tab_font_style   bold
inactive_tab_foreground #5c5c5c
inactive_tab_background #0a0a0a
inactive_tab_font_style normal
tab_bar_background      #000000
tab_bar_margin_width    0.0
tab_bar_margin_height   6.0 2.0
