# hackerman theme
window_padding_width 10

# Special
foreground #ddf7ff
background #090a13

# Black
color0  #3E4058
color8  #6a6e95

# Red
color1  #50f872
color9  #85ff9d

# Green
color2  #4fe88f
color10 #9cf7c2

# Yellow
color3  #50f7d4
color11 #a4ffec

# Blue
color4  #829dd4
color12 #c4d2ed

# Magenta
color5  #86a7df
color13 #cddbf4

# Cyan
color6  #7cf8f7
color14 #d1fffe

# White
color7  #85E1FB
color15 #ddf7ff

# Cursor
cursor              #ddf7ff
cursor_text_color   #0B0C16

# Selection
selection_foreground #ddf7ff
selection_background #191a23

# Tab bar
active_tab_foreground   #0B0C16
active_tab_background   #86a7df
active_tab_font_style   bold
inactive_tab_foreground #6a6e95
inactive_tab_background #14151f
inactive_tab_font_style normal
tab_bar_background      #090a13
tab_bar_margin_width    0.0
tab_bar_margin_height   6.0 2.0
